name: Emacs build and test
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  nix-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: jylhis
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build 
