name: Emacs build and test
on:
  push:
    paths:
      - 'flake.*'
      - 'sources/emacs/**/*'
    branches:
      - main
  workflow_dispatch:
jobs:
  nix-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build .#emacs
