name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - .github/**
      - .claude/**
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v5"
        with:
          persist-credentials: false
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "Jylhis/emacs"
          rolling: true
          visibility: "public"
          include-output-paths: true
